# 通知渠道选择,分别代表Telegram、Bark、Anpush、钉钉
# 1.TG
# 2.ANPUSH
# 3.BARK
# 4.DD
# 要填写具体的字母而不是数字
# 例如：
# PUSH_METHOD: "TG"
PUSH_METHOD: ""

# Telegram 相关
CHANNEL_ID: ""
TELEGRAM_BOT_TOKEN: ""

# Bark 相关
BARK_URL: ""
BARK_EXTRA: ""

# Anpush 相关
ANPUSH_TOKEN: ""
ANPUSH_CHANNEL: ""

# 钉钉 token
DD_BOT_TOKEN: ""
DD_BOT_SECRET: ""

# 账号授权相关
USERNAME: ""
PASSWORD: ""

# 是否是 Github Action
GITHUB: false

# 程序设置
# 1.优选模式 仅适用于西校区图书馆的三个自习室，个人优选了有插座的位置。
# 2.指定模式 请预先根据 json/seat_info 中各个自习室的真实位置('name')获取座位代号('id')，请输入对应自习室的对应 id
# 3.默认模式 全随机预约，速度最快，成功的概率最大
# 4.自动签退 2024-03-15 系统关闭了10点后自动签退的功能，目前3次不签退将会被加入黑名单，所以新增了一个自动化签退的模式
# 5.重新预约 重新预约当前已经预约的座位
MODE: "2"
SEAT_ID: # 这里只需要填首位号，函数会在这个范围内生成随机座位号
  - 7192
  - 7215
DATE: "tomorrow"
CLASSROOMS_NAME:
  - 西校区图书馆-三层自习室