# 通知渠道选择
PUSH_METHOD: "ANPUSH"

# Telegram 相关
CHANNEL_ID: ""
TELEGRAM_BOT_TOKEN: ""

# Bark 相关
BARK_URL: ""
BARK_EXTRA: "?icon=https://cdn.sakurasep.site/Website/new_avatar_256.png"

# Anpush 相关
ANPUSH_TOKEN: ""
ANPUSH_CHANNEL: ""

# 账号授权相关
USERNAME: ""
PASSWORD: ""

# 是否是 Github Action
GITHUB: True

# 程序设置
MODE: "1"
SEAT_ID:
  - 7520
  - 7543
DATE: "tomorrow"
CLASSROOMS_NAME: 西校区图书馆-五层自习室
